http_server:
  address: "192.168.0.163"
  port: "8443"
  tls_cert_dir: "certs"
  cert_file: "certs/cert.pem"
  key_file: "certs/key.pem"

mongodb:
  host: "localhost"
  port: "27017"
  database: "senior_project"
  # username: ""  # Take it or leave it
  # password: ""  # same here

dragonflydb:

zap_logger:
  development: true # development : true , production : false
  level: "debug"
  encoding: "json"
  log_dir: "./logs"
  log_file: "app.log"

lumberjack:
  max_size: 100 #100MB
  max_backups: 10
  max_age: 30 #30 days
  compress: true # useing Gzip

jwt_auth:
  # 512 bit secret key
  secret: "1e029cd5b07b984ef3afc2bea61a6730edd5cfdb5480d4016b386ea68b545dd54723ac7804aefc54958b4229fa78cb7f30eafe6e81bf2bf7719b9a1d37206911"
