http_server:
  address: "localhost"
  port: "8443"
  tls_cert_dir: "certs"
  cert_file: "certs/cert.pem"
  key_file: "certs/key.pem"

mongodb:
  host: "localhost"
  port: "27017"
  database: "senior_project"
  # username: ""  # Take it or leave it
  # password: ""  # same here

dragonflydb:

zap_logger:
  development: true # development : true , production : false
  level: "debug"
  encoding: "json"
  log_dir: "./logs"
  log_file: "app.log"

lumberjack:
  max_size: 1 #100MB
  max_backups: 10
  max_age: 30 #30 days
  compress: true # useing Gzip
